# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: julessainthorant <marvin@42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/03/28 15:21:10 by julessainthor     #+#    #+#              #
#    Updated: 2024/03/28 15:21:41 by julessainthor    ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRC = srcs/ft_display_file.c

all:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)

clean:
	rm -rf *.o

fclean:	clean
	rm -rf $(NAME)

re:	fclean all
